### ISSUE TITLE
Publish 4.2.2 version on crates.io

### ISSUE THREAD

**Issue by eldruin** [serialport/serialport-rs#115]
I have prepared a new patch release because of @KnorrFG asked for it. See #113 , #114 
However, I am not authorized to publish on crates.io.
Could somebody publish the state as of the [4.2.2 tag](https://github.com/serialport/serialport-rs/releases/tag/v4.2.2)?
Maybe @jessebraham ?

**Comment by sirhcel** [comment]
Thank you for inviting us on crates.io @jessebraham! Thank you for preparing this release @eldruin! Published [4.2.2](https://crates.io/crates/serialport/4.2.2) right now.

**Comment by eldruin** [comment]
Thank you @sirhcel and @jessebraham!
