### ISSUE TITLE
timeout has a different behavior on windows.

### ISSUE THREAD

**Issue by jessebraham** [serialport/serialport-rs#13]
This issue was migrated from GitLab. The original issue can be found here:
https://gitlab.com/susurrus/serialport-rs/-/issues/90
---
On linux, read will wait for serial port data until data is read in or timeout.
But in windows, read will block until it times out. If there is data in this process, it will return after timeout.

Is this a mistake in my usage, or a bug?

**Comment by sirhcel** [comment]
This sounds like the behavior we have finally fixed with #79.
