### ISSUE TITLE
Outdated documentation for TTYPort

### ISSUE THREAD

**Issue by Teufelchen1** [serialport/serialport-rs#180]
Hello!

I got confused by this comment and spend unnecessary time figuring out what I am doing wrong.
My suggestion is to change the documentation to:
```
However, this struct should not be instantiated directly by using TTYPort::open(),
instead use the cross-platform serialport::new(). Example:
`let mut port = serialport::new("/dev/ttyS0", 115200).open().expect("Error");`
```
https://github.com/serialport/serialport-rs/blob/09bfb98b00a86d2e4a53d4758f4e91f503b07044/src/posix/tty.rs#L36-L39

**Comment by sirhcel** [comment]
Good catch. Thank you! Would you mind opening a PR to iron this out?

**Comment by Teufelchen1** [comment]
Can do!
