### ISSUE TITLE
Missing COM ports in Windows

### ISSUE THREAD

**Issue by Crzyrndm** [serialport/serialport-rs#81]
Crate version is latest published (4.2.0)

I have a USB connected cell modem that enumerates in windows as 5 COM ports. On some computers, all of these are listed in device manager under "Ports (COM & LPT)" while on others, 2 of the ports only show up under "Modems".
![image](https://user-images.githubusercontent.com/8765278/221045932-6fa5dec4-f9dd-4d77-b53b-21b8356f22e7.png)
In ^^, COM5 and COM7 are the "modem" ports

* Those two ports are never listed by `serialport::available_ports()`
* YAT / TeraTerm find both of the ports (YAT with a name, TeraTerm has no info)
* https://docs.rs/serial2/latest/serial2/struct.SerialPort.html#method.available_ports does list those two ports on all tested computers

It would greatly simplify the hack I currently have in place to find the modem ports if those "modem" ports could also be listed

**Comment by DanielJoyce** [comment]
Yeah, for some reason serial port rs tends to skip those ports associated with modems, happens on linux too ( TTYACMx ), though opening a modem as a serial port is supported and supposed to work, so you can configure the modem.
